name: ci
on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - name: Install dependencies
        run: mix deps.get

      - name: Lint
        run: mix credo --strict

      - name: Test
        run: mix test

      - name: Format check
        run: mix format --check-formatted

      - name: Build doc
        run: mix docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main
          folder: doc
