name: ci
on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.2'

      - name: Cache Elixir
        uses: actions/cache@v2
        env:
          cache-name: cache-elixir-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Lint
        run: mix credo --strict

      - name: Test
        run: mix test

      - name: Format check
        run: mix format --check-formatted

      - name: Build doc
        run: mix docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main
          folder: doc
